### ISSUE TITLE
Is it possible to use Symfony Helpers (i.e. Questions etc.)?

### ISSUE THREAD

**Issue by rommsen** [webmozart/console#16]
Hi,

awesome library. 

I am thinking of ditching symfony console in favor of this one. But we make heavy usage of Symfonys Helpers (http://symfony.com/doc/current/components/console/helpers/questionhelper.html etc.). Here: https://github.com/webmozart/console/issues/7 it says that its available but I am not sure how to use it.

I was thinking about 
```php
public function handleAdd(Args $args, IO $io, Command $command)
{
    $helper = new QuestionHelper();
    $question = new ChoiceQuestion(
        'Please select your favorite colors (defaults to red and blue)',
        array('red', 'blue', 'yellow'),
        '0,1'
    );
    $question->setMultiselect(true);
    $colors = $helper->ask($io->getInput(), $io->getOutput(), $question);
```
but I get
`QuestionHelper::ask() must implement interface Symfony\Component\Console\Input\InputInterface, instance of Webmozart\Console\Api\IO\Input given`

Is it correct that I can not use the helpers?

**Comment by rommsen** [comment]
Ok I dug a bit into the code. I got it working but it feels very cumbersome:
```php
$colors = $helper->ask(new ArgsInput($args->getRawArgs(), $args), new IOOutput($io), $question);
```
Is this the intended way of doing this or does it work just by chance? If this is intended I could provide a PR for updating the README.

**Comment by webmozart** [comment]
@rommsen Yes, this is indeed the way you would do this. Since Symfony and this package have different APIs, there's nothing I can do but providing adapters. Of course, I could also create adapters for all the helpers with "nice APIs", but then there's always a new feature that is provided by Symfony that hasn't been added to this package yet. So, while a bit more cumbersome, I think the current approach is the most flexible one.

If there's an API that you use many times in your code, consider using traits:

~~~php
trait QuestionTrait
{
    protected function ask(Args $args, IO $io, Question $question)
    {
        // You could cache these instances, but you probably won't need it
        $helper = new QuestionHelper();

        return $helper->ask(new ArgsInput($args->getRawArgs(), $args), new IOOutput($io), $question);
    }
}

class MyCommandHandler
{
    use QuestionTrait;

    public function handle(Args $args, IO $io)
    {
        $question = new ChoiceQuestion(
            'Please select your favorite colors (defaults to red and blue)',
            array('red', 'blue', 'yellow'),
            '0,1'
        );

        $question->setMultiselect(true);

        $colors = $this->ask($args, $io, $question);
    }
}
~~~

**Comment by rommsen** [comment]
@webmozart Thanks for coming back to this. I have no problem doing it this way but I had to crawl around the code to find a solution.  What do you think about a small addition to the docs?

Btw: Today I released my first open source Gedöns ever: https://twitter.com/R0MMSEN/status/719546083223973888 

Thanks for providing the base for it!

**Comment by webmozart** [comment]
@rommsen Yes, you're right, this should be added to the documentation. Could you maybe provide a PR?

**Comment by rommsen** [comment]
@webmozart done: https://github.com/webmozart/console/pull/17
