### ISSUE TITLE
Wrong display of long option description

### ISSUE THREAD

**Issue by sstok** [webmozart/console#19]
When I add an option with a long description the text wraps incorrectly.

See the description of the `--project-folder` option.
![screen-img](https://cloud.githubusercontent.com/assets/904790/15990238/b517115e-308d-11e6-9e5b-c4f209a25f8c.png)

``` php
->addOption(
    'project-folder',
    null,
    Option::OPTIONAL_VALUE,
    'The root folder of the project, this is where the ".dancer" folder is located. '.
    'When omitted the folder is automatically searched by the first occurrence of the ".dancer" folder
    in the parent directory structure, and falls back to the current working.'
)
```

**Comment by webmozart** [comment]
Thanks for reporting this issue! :) I *thought* this worked.. could it be an issue that depends on the system? Would you like to work on that?

**Comment by sstok** [comment]
I will try to have at it in the weekend 👍

**Comment by jakubthedeveloper** [comment]
Sorry for digging this 5-yo thread but I just came across it and I see that the problem is just in the code from the post, there is a line break and some extra spaces. There should be a string concatenation as it is between first and second line of the parameter description:

```php
->addOption(
    'project-folder',
    null,
    Option::OPTIONAL_VALUE,
    'The root folder of the project, this is where the ".dancer" folder is located. '.
    'When omitted the folder is automatically searched by the first occurrence of the ".dancer" folder ' .
    'in the parent directory structure, and falls back to the current working.'
)
```

**Comment by sstok** [comment]
![years of academy training wasted](https://i.imgflip.com/4/39y0tu.jpg)

😄 thanks
