### ISSUE TITLE
Any widget like ProgressBar,confirm,select etc. like yii2 Concole  component did.

### ISSUE THREAD

**Issue by ihipop** [webmozart/console#7]
see what yii2 have
>
clearScreen
clearScreenBeforeCursor
saveCursorPosition
moveCursorUp
updateProgress
select
error
beginAnsiFormat
xtermBgColor
moveCursorDown
stdin
startProgress
scrollDown
scrollUp
ansiFormatCode
renderColoredString
input
moveCursorNextLine
showCursor
wrapText
ansiToHtml
output
stdout
clearLine
endProgress
confirm
hideCursor
isRunningOnWindows
moveCursorForward
restoreCursorPosition
BaseConsole
ansiFormat
xtermFgColor
ansiStrlen
getScreenSize
clearLineBeforeCursor
stderr
moveCursorBackward
streamSupportsAnsiColors
moveCursorTo
escape
clearLineAfterCursor
markdownToAnsi
moveCursorPrevLine
stripAnsiFormat
endAnsiFormat
clearScreenAfterCursor
prompt

I tinks this is very convenience to have the ability to draw these widgets
Any plan to adding this feature?

**Comment by sstok** [comment]
ProgressBar, confirm, select are already supported.
http://symfony.com/doc/current/components/console/helpers/index.html

Note that select is known under the question helper.

http://symfony.com/doc/current/components/console/helpers/questionhelper.html#let-the-user-choose-from-a-list-of-answers
http://symfony.com/doc/current/components/console/helpers/questionhelper.html#multiple-choices

**Comment by ihipop** [comment]
I see ，it's a full refactoring of the Symfony Console component
